### ISSUE TITLE
When will the code be released?

### ISSUE THREAD

**Issue by ldkong1205** [ADLab3Ds/TiG-BEV#1]
@ZrrSkywalker, thank you for open-sourcing your work! I wonder when will the code be officially released. Is there an estimated time for this?

**Comment by ZrrSkywalker** [comment]
Thanks for your interest in our work. We are still working on this project with more baseline models and will open-source it as soon as possible, maybe 1~2 months. Thank you for waiting.

**Comment by ldkong1205** [comment]
> Thanks for your interest in our work. We are still working on this project with more baseline models and will open-source it as soon as possible, maybe 1~2 months. Thank you for waiting.

Noted with thanks
