### ISSUE TITLE
Code understanding

### ISSUE THREAD

**Issue by CXT-666** [ADLab3Ds/TiG-BEV#4]
self.get_gt_sample_grid(gt_bboxes_3d[sample_ind].enlarged_box(self.enlarge_width).corners[bbox_ind][[0,2,4,6],:-1]).to(device)
can't understand

**Comment by Lambert-hpx** [comment]
Hello! Thank you for your concern about our work! I post some details below. 
(1) gt_bboxes_3d[sample_ind] : Get all gt bboxes in a certain frame.
(2) enlarged_box(self.enlarge_width) : Enlarge all gt bboxes with "self.enlarge_width" to cover a small portion of the background at the edge of the object.
(3) corners[bbox_ind][[0,2,4,6],:-1] : Get (x, y) of the four corner points of a certain bbox.
Then pass corners to "self.get_gt_sample_grid" to get sampling grid inside the bbox.
Hope this helps you!

**Comment by CXT-666** [comment]
你好，非常感谢你的回答。想再请教一个问题，bevdet在构建bevt特征时 ：将坐标中心点移到了左下角
           geom_feats = ((geom_feats - (self.bx - self.dx / 2.)) / self.dx).long()
所以在提取bbox中的特征点时也是将xy坐标中心移到左下角得到需要采样的特征在bev特征中的位置。可以这样理解吗？

centerpoint提取点云特征时也是将坐标中心进行移动了吗？我没有学过点云相关的算法。请问pointpillar构建的bev特征是以lidar坐标系为原点吗？
 grid[:,:,0] = torch.clip(((grid[:,:,0] - (self.img_view_transformer.bx[0].to(grid.device) - self.img_view_transformer.dx[0].to(grid.device) / 2.)) / self.img_view_transformer.dx[0].to(grid.device) / (self.img_view_transformer.nx[0].to(grid.device)-1))*2.0 - 1.0 ,min=-1.0,max=1.0)
        grid[:,:,1] = torch.clip(((grid[:,:,1] - (self.img_view_transformer.bx[1].to(grid.device) - self.img_view_transformer.dx[1].to(grid.device) / 2.)) / self.img_view_transformer.dx[1].to(grid.device) / (self.img_view_transformer.nx[1].to(grid.device)-1))*2.0 - 1.0 ,min=-1.0,max=1.0)
